version: "3"

services:
  db:
    image: postgres:15
    container_name: gitea_postgres
    restart: always
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea123
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitea-net

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    depends_on:
      - db
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
      DB_TYPE: postgres
      DB_HOST: db:5432
      DB_NAME: gitea
      DB_USER: gitea
      DB_PASSWD: gitea123
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - gitea-net

  runner:
    image: gitea/act_runner:latest
    container_name: gitea_runner
    depends_on:
      - gitea
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./runner:/data
    command: >
      sh -c 'if [ ! -f /data/.runner ]; then
      /usr/local/bin/act_runner register --instance http://gitea:3000 --token v3tF9S4EXxPyH3KSBPcj5g2RzbKiiaM0G92WRTu9 --name docker-runner --labels docker;
      fi;
      /usr/local/bin/act_runner daemon'
    networks:
      - gitea-net

networks:
  gitea-net:
    driver: bridge
